
version: 2

sources:
  - name: snowflake_source
    schema: staging
    description: "snowflake staging layer"
    tables:
      - name: orders
        description: "store order dataset"
        columns:
          - name: order_id
            description: "The primary key for this table"
            data_tests:
              - unique
              - not_null
          - name: customer_id 
            description: A unique customer ID
            tests:
              - unique
              - not_null
          - name: order_date
            description: A random date within the current year
          - name: status
            description: A randomly selected order status, such as CREATED, SHIPPED, DELIVERED, or CANCELLED
          - name: product_id
            description: A unique product ID
          - name: quantity
            description: A random quantity between 1 and 5
          - name: price
            description: A random price between 10 and 500
          - name: total_amount
            description: This is calculated as quantity * price

models:
  - name: orders 